# Generated by Django 3.2.2 on 2021-06-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20210604_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='past_records',
        ),
        migrations.AddField(
            model_name='bag',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
