# Generated by Django 3.2.2 on 2021-06-05 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0003_auto_20210605_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='user_name',
        ),
        migrations.AddField(
            model_name='bag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
